//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediateka.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Event
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Event()
        {
            this.EventExecutor = new HashSet<EventExecutor>();
            this.EventSkill = new HashSet<EventSkill>();
            this.MaterialEvent = new HashSet<MaterialEvent>();
            
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateTime { get; set; } = DateTime.Now;
        public System.DateTime Deadline { get; set; } = DateTime.Now.AddDays(1);
        public string City { get; set; }
        public int StatusId { get; set; }
        public int EventPlannerId { get; set; }
        public string CommentModerator { get; set; }
        public int Salary { get; set; }
    
        public virtual EventPlanner EventPlanner { get; set; }
        public virtual StatusEvent StatusEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventExecutor> EventExecutor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EventSkill> EventSkill { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialEvent> MaterialEvent { get; set; }
    }
}
