//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediateka.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediatekaEntities : DbContext
    {
        public MediatekaEntities()
            : base("name=MediatekaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Event> Event { get; set; }
        public virtual DbSet<EventExecutor> EventExecutor { get; set; }
        public virtual DbSet<EventPlanner> EventPlanner { get; set; }
        public virtual DbSet<EventSkill> EventSkill { get; set; }
        public virtual DbSet<Executor> Executor { get; set; }
        public virtual DbSet<ExecutorSkill> ExecutorSkill { get; set; }
        public virtual DbSet<MaterialEvent> MaterialEvent { get; set; }
        public virtual DbSet<Moderators> Moderators { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Skill> Skill { get; set; }
        public virtual DbSet<StatusEvent> StatusEvent { get; set; }
        public virtual DbSet<StatusExecutor> StatusExecutor { get; set; }
        public virtual DbSet<SwearWords> SwearWords { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeMsg> TypeMsg { get; set; }
    }
}
