//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediateka.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reviews
    {
        public int Id { get; set; }
        public string ContentMsg { get; set; }
        public int EvenPlannerId { get; set; }
        public int ExecutorId { get; set; }
        public int TypeMsgId { get; set; }
        public int Rating { get; set; }
    
        public virtual EventPlanner EventPlanner { get; set; }
        public virtual Executor Executor { get; set; }
        public virtual TypeMsg TypeMsg { get; set; }
    }
}
